### ISSUE TITLE
SPIKE [12]: Translation workflow requirements

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#66]

**Comment by klappy** [comment]
Temporary Workflow:

Door43-catalog is the owner of the published repo.
STR - is the what is approved then merged/published to catalog.
Organization - is the owner of the repo that users will fork from.
User - is the owner of the repo that they work from.

## Forking:
1. Organization owner needs a fork of each repo from the STR owner.
2. The user needs a fork of the repo from the Organization to work from.

## Editing:
1. User opens the repo after they have forked it and it loads the repo including the translations.
2. They edit and save their translations.

## Pull Requests 
1. User submits a PR from their repo to the organization's repo.
2. After organization merges all PRs from user, they submit a PR to STR for publishing.
3. STR is reviewed and then published to Catalog by merging another PR to Catalog.

## Troubleshooting
- If user does not see existing translation work, check to make sure fork was created before editing.
- If fork was made, check to see if other translated files exist, this may be a new one.
- If fork was not made, user must delete their repo and fork from Organization.

**Comment by klappy** [comment]
Discussed a need to hide all fields that take up space that should not be translated.

**Comment by jag3773** [comment]
(e.g. OrigQuote should be hidden by default for a translation workflow)

**Comment by birchamp** [comment]
Add a dropdown for organizations from the gitea-react-toolkit.

**Comment by klappy** [comment]
Branch workflow for Editing source English content appears to fit well for its use case. This can help guide the ideal feel for translation branch workflow.

1. User is a member of an organization on DCS and has write access to necessary repositories.
2. Organization has a repo of the appropriate name and file structure that matches English source 100%.
3. User logs in like edit workflow.
4. User *chooses organization* like edit workflow.
5. User selects language (limited to available language/resource repos in org).
6. User selects resource (limited to available language/resource repos in org).
7. User selects file to edit translation like edit workflow.

This can unify the edit and translation workflow as the only difference for editing is the choice of unfoldingWord as the organization and the selection of English as the language and the rest is identical. Behind the scenes it allows one logical path to handle both use cases.

**Comment by klappy** [comment]
@birchamp @jag3773 What are your thoughts on the above proposed workflow to unify Edit/Translate to both use Organization's Repo with Branch workflow?

**Comment by birchamp** [comment]
DoD: Get approval from @jag3773 and @birchamp and create Epic/Issues

**Comment by jag3773** [comment]
For the near term I think 1-2 are OK.  Longer term tC Create needs to abstract step 2. and allow the user to do it right from the app.  Maybe step 4 provides a list of organizations that a user is a part of and then a link to "Create New".

I think 5. should be any language, otherwise how will they start a new project?

I think 6. should rather be keyed off of unfoldingWord's list of "templates".  I think this should go before step 5 also.  (Select resource then select language.)

**Comment by klappy** [comment]
1. User is a member of an organization on DCS and has write access to necessary repositories.
2. User logs in like edit workflow.
3. Organization either:
    a. Has a repo of the appropriate name and file structure that matches English source 100%.
    b. A new blank repository is created in which translated files will populate.
4. User *chooses organization* (can also be done for edit workflow).
    - Include drop down of existing Organization membership.
    - Include link to DCS create new Organization (https://bg.door43.org/org/create).
5. User selects resource (limited to available language/resource repos in org).
6. User selects target language.
    - Existing projects which are limited to available language/resource repos in org.
    - New projects which cover all languages that are not already created.
7. User selects file to edit translation like edit workflow.

@jag3773 This should include the necessary modifications from your comment above.

**Comment by klappy** [comment]
### Tasks
- [ ] Gitea RCL: Implement core functions for user's organizations.
- [ ] Gitea RCL: Implement components for organizations list/selection (with create new link).
- [ ] tC Create: Implement organization selection in Stepper after User login.
- [ ] tC Create: Swap Resource and Language selection steps in Stepper.
- [ ] tC Create: Adapt logic to only use organization's name and user's branch instead of user for repository for all use cases.

**Comment by klappy** [comment]
Created issues #125 and #126.
